/** Isolated UI checks; native titlebar hit test without moving the desktop cursor. */
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2), option = key => args.includes(key) ? args[args.indexOf(key)+1] : undefined;
const require = createRequire(import.meta.url);
const { _electron } = require(require.resolve('playwright', { paths:[option('--playwright-root') || root] }));
const directory = path.join(root,'.runtime/benchmarks',`workspace-design-${Date.now()}`), data = path.join(directory,'profile');
mkdirSync(path.join(data,'config'),{recursive:true});
writeFileSync(path.join(data,'config/local.json'),JSON.stringify({provider:'local',voice:{voice_mode:'silent'},stt:{provider:'disabled'},hotkey:'Control+Alt+F6',cancel_hotkey:'Control+Alt+F7'}));
const report={checks:[],errors:[]};let app,page,design;
const emit = events => app.evaluate(({BrowserWindow},events) => {const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('window=chat'));events.forEach(e=>w.webContents.send('ayana:event',{protocol_version:1,...e}));},events);
const adjust=(label,value)=>design.getByLabel(label,{exact:true}).evaluate((node,value)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(node,String(value));node.dispatchEvent(new Event('input',{bubbles:true}));node.dispatchEvent(new Event('change',{bubbles:true}));},value);
try {
 app=await _electron.launch({executablePath:option('--packaged')||path.join(root,'apps/desktop/node_modules/electron/dist/electron.exe'),args:[...(option('--packaged')?[]:[path.join(root,'apps/desktop')]),`--user-data-dir=${data}`],env:{...process.env,AYANA_DATA_DIR:data,AYANA_REPOSITORY_ROOT:option('--packaged')?'':root,AYANA_PYTHON:option('--packaged')?'':path.join(root,'.venv/Scripts/python.exe')},timeout:30000});
 app.process().stderr.on('data',v=>{if(v.toString().includes('TEST_UNCAUGHT'))report.errors.push(v.toString());});
 await app.evaluate(({app})=>{app.__testErrors=[];process.on('uncaughtException',e=>{app.__testErrors.push(String(e));console.error('TEST_UNCAUGHT',String(e));});});
 const windows=await app.windows();page=windows.find(w=>w.url().includes('window=chat'));design=windows.find(w=>w.url().includes('window=design'));
 windows.forEach(w=>w.on('pageerror',e=>report.errors.push(e.message)));
 await page.waitForFunction(()=>window.ayana.getState().then(s=>s.connected),null,{timeout:30000});
 await page.waitForFunction(()=>document.querySelector('img.character')?.naturalWidth>0);
 await page.getByRole('region',{name:'对话与工作区',exact:true}).waitFor();
 const scene=await page.locator('.companion-workspace').evaluate(n=>{const s=getComputedStyle(n);return{border:s.borderTopWidth,background:s.backgroundColor,shadow:s.boxShadow};});
 assert.deepEqual(scene,{border:'0px',background:'rgba(0, 0, 0, 0)',shadow:'none'});
 assert.equal(await page.getByLabel('查看上下文',{exact:true}).count(),0);
 report.checks.push('Captions share the portrait scene without an inner frame, background panel or history button');
 const header=await page.locator('.companion-title-drag-area').boundingBox();
 const native=await app.evaluate(({BrowserWindow,screen},header)=>{const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('window=chat')),b=w.getBounds();return{hwnd:w.getNativeWindowHandle().readUInt32LE(),point:screen.dipToScreenPoint({x:Math.round(b.x+header.x+header.width/2),y:Math.round(b.y+header.y+header.height/2)}),movable:w.isMovable()};},header);
 const hit=Number(execFileSync(path.join(root,'.venv/Scripts/python.exe'),['-c','from native.windows.win32 import Win32,ULONG_PTR; import ctypes as C,sys; a=Win32(); r=ULONG_PTR(); ok=a.user.SendMessageTimeoutW(int(sys.argv[1]),0x84,0,(int(sys.argv[2])&65535)|((int(sys.argv[3])&65535)<<16),2,1000,C.byref(r)); print(r.value if ok else -99)',String(native.hwnd),String(native.point.x),String(native.point.y)],{cwd:root,windowsHide:true}).toString().trim());
 report.native={...native,hit};assert.equal(hit,2,'Windows must identify the header as HTCAPTION.');assert(native.movable);
 assert.equal(await page.locator('.companion-drag-grip').count(),0);
 report.checks.push('Windows hit testing identifies the titlebar as its own draggable caption; custom grip is removed');

 await page.getByLabel('打开设计控件',{exact:true}).click();
 await design.getByRole('tab',{name:'便签',exact:true}).click();
 await design.getByLabel('便签背景',{exact:true}).selectOption('solid');await adjust('背景不透明度',100);
 await design.getByLabel('自选背景颜色',{exact:true}).evaluate(node=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(node,'#eee5d2');node.dispatchEvent(new Event('input',{bubbles:true}));node.dispatchEvent(new Event('change',{bubbles:true}));});
 await page.waitForFunction(()=>document.querySelector('.companion-note').dataset.tone==='light');
 assert.equal(await page.locator('.note-surface').evaluate(n=>getComputedStyle(n).opacity),'1');
 assert.equal(await page.locator('.note-surface').evaluate(n=>getComputedStyle(n).backgroundColor),'rgb(238, 229, 210)');
 await page.screenshot({path:path.join(directory,'solid-light.png'),omitBackground:true});
 await design.getByLabel('便签背景',{exact:true}).selectOption('minimal');
 assert((await page.locator('.note-surface').evaluate(n=>getComputedStyle(n).backgroundImage)).includes('gradient'));
 await design.getByRole('tab',{name:'立绘',exact:true}).click();await design.getByLabel('立绘站位',{exact:true}).selectOption('left');await page.evaluate(()=>window.ayana.previewDesign({portrait_x:-30,portrait_y:25}));
 await page.waitForFunction(()=>document.querySelector('.companion-note').dataset.portraitSide==='left');
 const portrait=await page.locator('.portrait-stage').boundingBox(),work=await page.locator('.companion-workspace').boundingBox();assert(portrait.x<work.x, 'Left preset positions the drawing on the left of the scene.');
 assert.equal(await page.locator('.portrait-stage').evaluate(n=>Number.parseFloat(n.style.top)),25);
 await design.getByRole('button',{name:'保存设计',exact:true}).click();await design.getByText('设计已保存',{exact:true}).waitFor();
 const saved=JSON.parse(readFileSync(path.join(data,'config/local.json'),'utf8')).companion_ui;assert.equal(saved.opacity,100);assert.equal(saved.portrait_x,-30);assert.equal(saved.portrait_y,25);assert.equal(saved.portrait_side,'left');assert.equal(saved.background_color,'#eee5d2');
 await design.getByLabel('收起设计控件',{exact:true}).click();
 report.checks.push('100% opacity, pure color, light-theme contrast and minimal artwork preview/save; left/right portrait position and X/Y offsets persist');

 await page.evaluate(()=>window.ayana.send({type:'turn.start',text:'请保留这条上下文记录'}));
 await page.waitForFunction(()=>document.querySelector('.cinematic-shot')?.textContent.includes('我在这里'));
 await page.waitForTimeout(6500);assert((await page.locator('.cinematic-memory-row.is-current').count())>0,'Completed latest text remains focused.');
 await page.screenshot({path:path.join(directory,'cinematic-live.png'),omitBackground:true});
 await page.getByLabel('你上一句说的话',{exact:true}).getByText('请保留这条上下文记录',{exact:true}).waitFor();
 assert((await page.locator('.cinematic-memory-row').allTextContents()).join('').includes('我在这里'));
 const count=await page.locator('.cinematic-memory-row').count();
 assert.equal(await page.locator('.cinematic-question').count(),1,'Question has an independent pinned layer.');
 assert.equal(await page.locator('.cinematic-memory .cinematic-question').count(),0);
 await page.screenshot({path:path.join(directory,'context.png'),omitBackground:true});
 await page.reload();await page.waitForFunction(()=>document.querySelector('.companion-shell')?.style.getPropertyValue('--portrait-x')==='-30px');
 await page.waitForFunction(count=>document.querySelectorAll('.cinematic-memory-row').length>=count,count);
 assert((await page.locator('.cinematic-question').textContent()).includes('请保留这条上下文记录'));
 const cid=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('window=chat')).webContents.executeJavaScript('window.ayana.getState().then(s=>s.events.filter(e=>e.type==="conversations.ready").at(-1).current.conversation_id)'));
 await emit([{type:'history.ready',history_conversation_id:'unrelated-topic',history:[{id:999,role:'user',text:'不该混入当前话题'}]}]);await page.waitForTimeout(100);
 assert(!(await page.locator('.companion-workspace').textContent()).includes('不该混入当前话题'));
 await page.evaluate(()=>window.ayana.send({type:'conversation.create',keep_materials:false}));await page.waitForFunction(()=>document.querySelectorAll('.cinematic-memory-row').length===0 && !document.querySelector('.cinematic-question'));
 assert.equal(await page.locator('.cinematic-memory-row').count(),0,'New topic cannot inherit previous transcript.');
 await page.evaluate(cid=>window.ayana.send({type:'conversation.select',conversation_id:cid}),cid);await page.getByLabel('你上一句说的话',{exact:true}).getByText('请保留这条上下文记录',{exact:true}).waitFor();
 report.checks.push('replies retire into scrollable history; latest user question stays outside that layer; reload and topic return restore records; late history cannot cross topics');
 assert.deepEqual(report.errors,[]);report.passed=true;
}catch(error){report.passed=false;report.failure=String(error);process.exitCode=1;if(page)await page.screenshot({path:path.join(directory,'failure.png'),omitBackground:true}).catch(()=>{});}
finally{if(app)await app.close();writeFileSync(path.join(directory,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({...report,directory},null,2));}
